### ISSUE TITLE
Build Failure on macOS M2 (arm64)

### ISSUE THREAD

**Issue by oneanime** [fabmax/physx-jni#85]
I’m trying to build the PhysX project (with JNI support) on my MacBook with Apple M2 chip, but the build fails during compilation. I’m using the jni-mac-aarch64 target.

the logs:

note: Run script build phase 'Generate CMakeFiles/ZERO_CHECK' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ZERO_CHECK' from project 'PhysXSDK')
note: Run script build phase 'Generate CMakeFiles/ALL_BUILD' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'ALL_BUILD' from project 'PhysXSDK')
note: Run script build phase 'CMake PostBuild Rules' will be run during every build because the option to run the script phase "Based on dependency analysis" is unchecked. (in target 'PhysXJniBindings' from project 'PhysXSDK')
** BUILD FAILED **

The following build commands failed:
	CompileC /Users/zxc/workspace/physx-jni/PhysX/physx/compiler/jni-mac-aarch64/build/SimulationController.build/debug/Objects-normal/arm64/ScVisualize.o /Users/zxc/workspace/physx-jni/PhysX/physx/source/simulationcontroller/src/ScVisualize.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'SimulationController' from project 'PhysXSDK')
	CompileC /Users/zxc/workspace/physx-jni/PhysX/physx/compiler/jni-mac-aarch64/build/SimulationController.build/debug/Objects-normal/arm64/ScStaticCore.o /Users/zxc/workspace/physx-jni/PhysX/physx/source/simulationcontroller/src/ScStaticCore.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'SimulationController' from project 'PhysXSDK')
	CompileC /Users/zxc/workspace/physx-jni/PhysX/physx/compiler/jni-mac-aarch64/build/SimulationController.build/debug/Objects-normal/arm64/ScSqBoundsManager.o /Users/zxc/workspace/physx-jni/PhysX/physx/source/simulationcontroller/src/ScSqBoundsManager.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'SimulationController' from project 'PhysXSDK')
	CompileC /Users/zxc/workspace/physx-jni/PhysX/physx/compiler/jni-mac-aarch64/build/SimulationController.build/debug/Objects-normal/arm64/ScSoftBodySim.o /Users/zxc/workspace/physx-jni/PhysX/physx/source/simulationcontroller/src/ScSoftBodySim.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'SimulationController' from project 'PhysXSDK')
	CompileC /Users/zxc/workspace/physx-jni/PhysX/physx/compiler/jni-mac-aarch64/build/SimulationController.build/debug/Objects-normal/arm64/ScTriggerInteraction.o /Users/zxc/workspace/physx-jni/PhysX/physx/source/simulationcontroller/src/ScTriggerInteraction.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'SimulationController' from project 'PhysXSDK')
	CompileC /Users/zxc/workspace/physx-jni/PhysX/physx/compiler/jni-mac-aarch64/build/SimulationController.build/debug/Objects-normal/arm64/ScSoftBodyShapeSim.o /Users/zxc/workspace/physx-jni/PhysX/physx/source/simulationcontroller/src/ScSoftBodyShapeSim.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'SimulationController' from project 'PhysXSDK')
	CompileC /Users/zxc/workspace/physx-jni/PhysX/physx/compiler/jni-mac-aarch64/build/SimulationController.build/debug/Objects-normal/arm64/ScSoftBodyCore.o /Users/zxc/workspace/physx-jni/PhysX/physx/source/simulationcontroller/src/ScSoftBodyCore.cpp normal arm64 c++ com.apple.compilers.llvm.clang.1_0.compiler (in target 'SimulationController' from project 'PhysXSDK')
(7 failures)

**Comment by fabmax** [comment]
Apparently the latest XCode update introduced new compiler warnings which are promoted to errors. I updated the buildscript to ignore them (https://github.com/fabmax/PhysX/commit/efa53f8117a5fac35a4d9014561daec9bc509036). Update the `PhysX` submodule and try rebuilding (it should work now):
```
./gradlew generateNativeProject
./gradlew buildNativeProject
```

**Comment by oneanime** [comment]
I'm still encountering the above error when using version 2.4.2, but it compiles successfully with version 2.6.0. Does this mean only the latest version is supported

**Comment by oneanime** [comment]
I'm still encountering the above error when using version 2.4.2, but it compiles successfully with version 2.6.0. Does this mean only the latest version is supported

**Comment by fabmax** [comment]
Yes, if you use an older version it will also use an older version of the native project, which does not have the latest fixes. But the differences between 2.4.2 and 2.6.0 aren't too large so you should be able to use that. And of course, if you don't need any custom modifications, you can simply use the prebuilt version, which already supports Apple ARM processors since a long time.
